media:
  input: images
  output: /images

content:
  - name: homepage
    label: Home Page (index.html)
    type: file
    path: index.html
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Content Body
        type: rich-text
        format: code